prepare v1.0.0 release
tokio-rs/bytes pull request #451
Opened 2020-12-19 11:48 UTC by aknuds1

2020-12-19 11:48 UTC, aknuds1 commented
@Darksonn How do I compile the changelog?

2020-12-19 11:52 UTC, Darksonn commented
Read [the list of commits](https://github.com/tokio-rs/bytes/commits/master) backwards until the last preparation PR.

2020-12-19 20:22 UTC, carllerche requested changes
Hey! Thanks for doing this. We are going to hold off doing the actual release until Tokio is ready for the release as well. However, we can merge most of this :+1: Some thoughts inline.

2020-12-19 20:22 UTC, carllerche commented on CHANGELOG.md
> +# 1.0.0 (December 19, 2020)
```suggestion
# 1.0.0 (unreleased)
```

2020-12-19 20:22 UTC, carllerche commented on Cargo.toml
> -publish = false
Revert this line.

2020-12-20 15:29 UTC, carllerche approved these changes

2020-12-20 15:31 UTC, merged